[View in Colaboratory](https://colab.research.google.com/github/anirbanghoshsbi/keras_tricks/blob/master/Converting_labels_to_one_hot_encoding.ipynb)

In [0]:
# Download the necessary packages
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [0]:
# here I have a categorical data of six different strings , I want it to be one hot encoded for use in DL
y = ['cat','rat','bat','sat','ate']
# convert the list to numpy
y = np.array(y)

In [0]:
# fit data
le = LabelEncoder().fit(y)


In [0]:
#transform and one hot encode it.
labels = np_utils.to_categorical(le.transform(y),6)

In [19]:
labels

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)

In [0]:
# Method 2 of the same
le = LabelEncoder()


In [25]:
# fit_and_transform the data using the fit_transform command
labels=le.fit_transform(y)
labels

array([2, 3, 1, 4, 0])

In [0]:
# pass it to the np_utils.to_categorical to get the result.
labels = np_utils.to_categorical(labels,6)

In [24]:
labels

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.]], dtype=float32)